version: "3.3"
networks:
  botnet: 
    ipam:
      config:
        - subnet: 172.16.0.0/19
    driver_opts:
      com.docker.network.bridge.name: botnet
services:     
    admin:
      build: admin
      networks:
        botnet:
           ipv4_address: 172.16.0.10
      ports: 
        - "65223:65223"
        - "65222:65222"

    daemon1:
      build: daemon
      networks:
      -  botnet
      environment:
        name: daemon1


    daemon2:
      build: daemon
      networks:
      -  botnet
      environment:
        name: daemon2

    daemon3:
      build: daemon
      networks:
      -  botnet
      environment:
        name: daemon3

    daemon4:
      build: daemon
      networks:
      -  botnet  
      environment:
        name: daemon4
    
    web:
      build: web
      networks:
       botnet:
           ipv4_address: 172.16.0.100